language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chinjs/chin-plugin-convert-svg
    branch: publish
  api_key:
    secure: QA4+Ec8KMhIAvYtgMyCkx+0MRgj/489e6Lp3pTJOH++hWYshfPV29TwEpkD8eUjp2HejKFlsTp5w2kgoEpsgrkCLb3lQKqYYxYWicIk612qngOK+/wRpirIevVdgPkxDAddP+vzov3ZZeRIfj5Bwod9+jTC49CtEk0VRLuARBiG4Udx0WQbAVrps0EIz5Fd80RE6HgYMknBF5zYNH9WoL/+qlCjf1MYq1lLoKn3kxlafs4nb4xXA9TxybjGPL8Qjn5PSkg2QtoZtdxEsFeT8igL2Zzq6qF9v92ul4kZa1thvvKdY5NDaB5xfY6UKMn+BKT9G4gn/Tw4G0DJuQonsYIHkfTZh6nCjEUQ4rgJFrDDeLctDNamZv84yBZ6ovDrQiBJr3B71tiqtxZWP9GrsL0K4kulPTZM/HJX1Te/8v7ZqdpYRa+OeJSfUSWJnX3bma/mGGccBSogqtchdiM07QvxRQovXvZwbUuKVof1UvV0lX+hC4RUYYdXmn9xsbF0XyCSL2I0arzNWV/x4+tl87YfrO5O9gjdvEQNYq0hhqQrX1zwuzgxQCppAABLyuSYIhYyj6L4B30/Ujkr2HprRG/qmi9vcs5050fSjTHM6U61WLXaBas/1ZhmiBRUM0MTc5FrN685rPGTlw9XAIflVyTxL9acIhU1/xNEHHE2RD2Q=
